### ISSUE TITLE
client parameters needed?

### ISSUE THREAD

**Issue by ekse** [BreakingMalware/Selfie#2]
The usage in the readme specifies to pass parameters (1 "") to the dynamorio client.

`drrun.exe -client "selfie.dll" 1 "" -- "malware.exe"`

Those parameters do not seem to be used by Selfie.

**Comment by BreakingMalware** [comment]
Selfie requires no args, thats why the "" are empty.

**Comment by ekse** [comment]
What is the 1 for ?
